-- AlterTable
ALTER TABLE `sizes` ADD COLUMN `cupId` INTEGER UNSIGNED NULL;

-- CreateTable
CREATE TABLE `cups` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `sizes` ADD CONSTRAINT `sizes_cupId_fkey` FOREIGN KEY (`cupId`) REFERENCES `cups`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
